### ISSUE TITLE
Tight rate limiting on inventory endpoint

### ISSUE THREAD

**Issue by joostvandermeer** [developersbolcom/developersbolcom.github.io#13]
A retailer has reported an issue with the rate limit on the inventory endpoint. He would expect at least 10 calls per limit to be possible, now only gets 1. Will be investigated with other bol.com teams to see if this can be changed.

**Comment by joostvandermeer** [comment]
Rate limit has been raised to ten.

**Comment by joostvandermeer** [comment]
Test

**Comment by michieldejong** [comment]
test
