### ISSUE TITLE
Offer endpoint isn't returning entityId on post

### ISSUE THREAD

**Issue by RCarisBuyBay** [developersbolcom/developersbolcom.github.io#15]
**Endpoint**

offers

**Problem**

According to the documentation page (https://api.bol.com/retailer/public/redoc/v3#operation/post-offer) we should receive a entityId immediately after posting our offer. I think this entityId is our unique bol offer id for this offer, but please correct me if i'm wrong.
On demo the creation of an offer isn't returning any entityId.

**Our request**

```
  [httplog] Connecting: api.bol.com:443
  [httplog] Sending: POST http://api.bol.com:443/retailer-demo/offers
  [httplog] Header: content-type: application/vnd.retailer.v3+json
  [httplog] Header: accept: application/vnd.retailer.v3+json
  [httplog] Header: authorization: Bearer *
  [httplog] Header: connection: close
  [httplog] Header: host: api.bol.com
  [httplog] Header: content-length: 372
  [httplog] Data {"ean":"5707119029520",
                            "referenceCode":"4a088503b526ee6cdf28",
                            "onHoldByRetailer":false,
                            "pricing":{"bundlePrices":[{"quantity":1, "price":"120.0"}]},
                            "stock":{"amount":1, "managedByRetailer":true},
                            "fulfilment":{"type":"FBR", "deliveryCode":"24uurs-15"},
                            "condition":{"name":"GOOD", "comment":"This product has slight wear indicating one time used. De verpakking is beschadigd."}}
  [httplog] Status: 202
  [httplog] Benchmark: 0.070431 seconds
  [httplog] Header: date: Tue, 12 Mar 2019 13:10:36 GMT
  [httplog] Header: server: Apache Tomcat
  [httplog] Header: x-xss-protection: 1; mode=block
  [httplog] Header: x-content-type-options: nosniff
  [httplog] Header: x-frame-options: SAMEORIGIN
  [httplog] Header: strict-transport-security: max-age=31536000
  [httplog] Header: x-application-context: Edge:8090
  [httplog] Header: content-type: application/vnd.retailer.v3+json;charset=UTF-8
  [httplog] Header: vary: Accept-Encoding,User-Agent
  [httplog] Header: connection: close
  [httplog] Header: transfer-encoding: chunked
  [httplog] Response: 
    {"id":1," eventType":"CREATE_OFFER","description":"Create an offer with ean 5707119029520.","status":"PENDING","createTimestamp":"2019-03-12T14:10:36.557+01:00","links":[{"rel":"self","href":"https://api.bol.com/retailer-demo/process-status/1","method":"GET"}]}
```
**The result we expected**

According the documentation we should at least receive entityId when we do a post to this endpoint. So if that's correctly the bug is in the response.

Another possibility is that an offer id is generated when the process status is 'SUCCESS' instead of 'PENDING'. But this is hard to find in the documentation and even harder to test because it's always returning status 'PENDING'. 
If this possibility is the way it should work, then the response from documentation should be changed.

**Comment by gvantuijl** [comment]
Hi,

Your last assumption is correct. An entityId is only generated when the status = SUCCESS. See my comment on ticket #12 as well. This is also described on our 'conventions' page (paragraph 'Asynchronous Processing'), which you can check at https://api.bol.com/retailer/public/conventions/index.html.

Does this provide sufficient information?

**Comment by jwalgemoed** [comment]
For convenience, I've added the text from the documentation below. Please let us know if this makes the situation clear, and if not, we'd love to hear any suggestions you might have on how to improve our documentation.

> In the case shown above, the executed action is the shipment confirmation of an order, so the entity-id (order id in this case) is known. Some actions (such as creating an inbound shipment for FBB) will return an idea upon completion of the process. For these actions, the entityId field will be null while in "PENDING" state, and only after the process transitions to "SUCCESS" the entityId field will be populated by the resulting value. For all other processes (update/delete type operations) the action can't be initiated without the id of the entity to update/delete.

**Comment by joostvandermeer** [comment]
I will move this issue to done. Please let us know if you have any follow-up questions, we can always re-open it.
