### ISSUE TITLE
value ALL for fulfilment_method parameter multiple methods

### ISSUE THREAD

**Issue by Coennie** [developersbolcom/developersbolcom.github.io#18]
The v2 api allowed the value 'ALL' for the fulfilment_method parameter on multiple methods to include both FBB and FBR. In the v3 version the parameter must be FBB or FBR, can you also include 'ALL'?

**Comment by jwalgemoed** [comment]
Hi Coennie, we will definitely look into this.

**Comment by joostvandermeer** [comment]
Hoi Coen,

Goede vraag. De API is erop bedacht om specifieke processen te ondersteunen. De gedachte is dat de verkoper de FBR-filtering gebruikt wanneer hij zelf zijn orders wil gaan afhandelen, en de FBB-filtering wanneer hij daar inzicht in wil.

Ik vrees dat we in de v3 voorlopig geen 'All'-filter mogelijk gaan maken. De list call is zo 'licht' mogelijk gemaakt, wat o.a. betekent dat hij nooit meer dan 1 service aan de achterkant aanroept. FBB-orders en FBR-orders zitten nu nog in 2 verschillende services. Het is de bedoeling dat die op een gegeven moment naar 1 service gaan, daarna zou een 'all'-filter mogelijk worden. Ik neem er een placeholder story voor op op de roadmap.

Groeten,

Joost
