### ISSUE TITLE
Return entityId of shipment item when shipping an order item

### ISSUE THREAD

**Issue by JeroenVanLeusden** [developersbolcom/developersbolcom.github.io#21]
### Description
Fetching shipping labels is a long running process that requires calling multiple endpoints.
Let's say we use the Magento 2 module (currently in development) and setup atleast two merchant accounts.
After pushing the shipments with a `shippingLabelCode` we can, after process status is success, fetch the shipping label.
We've shipped six orders, to fetch the labels we currently have to follow these steps:

1. Wait for process status to be complete (somewhere from couple seconds to minutes).
2. Fetch shipment list for both merchant A and B because the orders are coming from multiple merchant accounts.
3. In that list we'll find the shipment using the `orderItemId`.
4. We can now fetch the shipment itself.
5. Fetch `shippingLabelId` from shipment and request a shipping label pdf.

This process will take a fairly long time to complete. 

### Expected behavior
Return shipment id in process status after pushing shipment (same as offer).
Preferred behavior because this will allow us to standardize processing the process statuses.

_or_

Create endpoint to fetch shipment using `orderItemId`.

### Benefits
Bypass fetching the shipment list which will simplify and speedup the entire process.

### Additional information
Alternatively we could create a cron job in which we can process step 1, 2, 3 and 4.
I'm not sure what the exact rate limit is for these endpoints but if we process the shipments once every five minutes it will add that as an extra delay.

**Comment by jwalgemoed** [comment]
Thank you for the feedback! We are currently looking into what solution we feel works best for the API.

**Comment by idebruijn** [comment]
Picking up this issue

Suggested solution: 
* adding the transportId in get shipments
* adding filtering based on orderId in get shipment

**Comment by joostvandermeer** [comment]
Hi Jeroen,

The solution above has been implemented in production, this should fix your issue.

Please let us know if you have any more questions.
