### ISSUE TITLE
Support for multi-item returns

### ISSUE THREAD

**Issue by gvantuijl** [developersbolcom/developersbolcom.github.io#25]
_Please note: the following text describes an epic that is still being designed and planned by the retailer API team. The exact working of the endpoints may still be changed or even canceled based on retailer feedback and new insights during creation.
The information is published here with the goal to provide retailers with the opportunity to provide feedback._

**Background**
The next development cycle will concentrate on the topic 'returns'. Currently our customers can only announce and ship a return item individually. So, in case a customer ordered multiple items in one single customer order, the customer should register each item within that customer order for return individually. This results in two shipping labels and possibly two different transports and packages. 

We also see that some customers are adding all items to the same package using 1 single track and trace. In that case, it is hard to track each item individually as there is only 1 shipment and corresponding reference available.

With the new multi-item return endpoints, customers can register and send back multiple <em>return items</em> in one package (one <em>return)</em>.

Additionally, we wish to improve the return flow by enabling retailers to retrieve a return based on a track&trace-code, and to create an unannounced return using the API.

**New endpoints**
To facilitate multi-item returns, we expect to create three new endpoints:
- New “get single return”: allows searching on rma id and return id. It should always give back an entire return including its underlying return items. In case you search on return id, you will get the entire return. In case you search on rma id, you will get the entire return that contains the corresponding return item (rma id).
- New “get returns”: this endpoint should be like the existing ‘get returns’ endpoint, with the following change: The message structure should follow the new multi-item structure: a return with a corresponding return id, with multiple underlying return items with rma id’s.
- Create unannounced return: this endpoint should enable retailers to create and handle return items with one single request.

**Comment by mroosendaal** [comment]
Solved
