### ISSUE TITLE
[BUG] Retrieving open orders fails with error 500

### ISSUE THREAD

**Issue by jwalgemoed** [developersbolcom/developersbolcom.github.io#26]
In some exotic cases, retrieving orders from the retailer API results in an error 500 being returned. This prevents the retailer from retrieving orders.

The bug has been reported in the cases where fulfilmentMethod FBB is used, but can potentially also occur with fulfilmentMethod FBR.

Please let us know if you are experiencing these (or other) issues when retrieving open orders through the API.

**Comment by jwalgemoed** [comment]
We've identified the issue in the API and are working towards a fix.

**Comment by idebruijn** [comment]
The problem is solved and released today.
