### ISSUE TITLE
Daily Timeout errors

### ISSUE THREAD

**Issue by Nick-Enthoven** [developersbolcom/developersbolcom.github.io#27]
While not an immediate incident, it is something that happens every day and is very apparent when using the Magento Module.

The Magento module logs whenever the module is unable to retrieve orders from bol.com, it lists this as an error in the Magento Notifications screen.
![image](https://user-images.githubusercontent.com/36893549/55535905-b7416c00-56b8-11e9-8d15-2bf7e27e61b4.png)

`Server error: `GET https://api.bol.com/retailer/orders?page=1&fulfilment-method=FBR` resulted in a `504 The downstream service failed to respond in time.: ` response: (truncated...)`

It seems that at least once a day the orders are not available for retrieval, sometimes more often than once a day. Fortunately the orders can still be retrieved at a later time.

These errors correspond to a Timeout in Kibana logs at the same time.

**Comment by idebruijn** [comment]
Under investigation.

**Comment by joostvandermeer** [comment]
Issue has been fixed. Errors should no longer occur.
