### ISSUE TITLE
Validation on Post product content

### ISSUE THREAD

**Issue by bcvdt** [developersbolcom/developersbolcom.github.io#60]
Hi,

What kind of validation is done when submitting a product batch via https://api.bol.com/retailer/public/redoc/v4
Could, for example, an invalid list item value cause a http 400 error? And as a result would the entire batch not be processed?

**Comment by stetteroox** [comment]
Hi @bcvdt 

Could you extend on what you mean by invalid list item?

If you get back a 400 it means the request send was invalid, so nothing will get processed at all.

**Comment by duncanlew** [comment]
Hi bcvdt, 

The entire request will only be rejected if

- an invalid language is supplied (406 error)
- property internalReference in the list is not unique.
- required fields not supplied

When you request goes through, deeper attribute value validations will be executed. I would like to refer to you to the error codes in the validation reports: https://developers.bol.com/api-v4-product-content/

**Comment by bcvdt** [comment]
Hi @duncanlew 

Thanks for your reply.
Why is the validation of required fields already done here? Shouldn't this be in validation report?

**Comment by duncanlew** [comment]
We expect the request to adhere to the required fields in the model, otherwise there's no use to start further processing. This to prevent giving very specific feedback on malformed payloads. 

For example, without the language field, we wouldn't know under which type of language to start the processing.
