### ISSUE TITLE
[Improvement] Return an informative message on the demo environment and not only a 500 is a request is not matched precisely. [2293, 2088]

### ISSUE THREAD

**Issue by idebruijn** [developersbolcom/developersbolcom.github.io#8]
I experience problems on the demo environment and it's not clear why:

1)	When I do a get bulk commissions call that isn't matched precisely I get a 500 error message.

2)	When I do an inbound shipment list request with query params (examples: ?page=2 of ?state=ArrivedAtWH) I also get a 500 error message.

**Comment by idebruijn** [comment]
All calls on the demo environment that do not match exactly return a http 500 error message.

Possible improvements:

1) Extend demo environment chapter on: https://api.bol.com/retailer/public/conventions/index.html on how the demo environment works.
2) Return a response that is more clear then a http 500 message.

**Comment by idebruijn** [comment]
If a request does not match exactly with the documented request on the demo environment currently a problem with status 500 is returned.

{
    "type": "http://api.bol.com/problems",
    "title": "Internal Server Error",
    "status": 500,
    "detail": "Internal server error handling request.",
    "host": "Instance-002",
    "instance": "https://api.bol.com/retailer-demo/orders?page=WRONG_PAGE"
}

This has been added to the Demo environment chapter: https://api.bol.com/retailer/public/conventions/index.html

**Comment by jwalgemoed** [comment]
The documentation is clear on the functionality and limitations offered by the test endpoints. Feel free to provide us with feedback on its contents and the workings of the test endpoints, but for now this is low priority and may be addressed at a later time in the future.
