### ISSUE TITLE
[Improvement] Query param "period" get invoices [2357]

### ISSUE THREAD

**Issue by idebruijn** [developersbolcom/developersbolcom.github.io#9]
Query param "period" in get invoices is not ISO-8601 compliant but YYYY-mm-dd. A timeslot solution as used in Post Inbound Shipment is requested.

**Comment by jwalgemoed** [comment]
It's correct that this parameter is not consistent with the way we are currently handling dates in the API. We are going to make a (breaking!) changes in the API that will entail the following:

- Removal of period request parameter
- Addition of two [ISO-8601](https://nl.wikipedia.org/wiki/ISO_8601) request parameters (periodStart, periodEnd)
- Validations that will validate the input in conjunction (date format validation, period length validation, start not before end, etc.)

Implementation will start as soon as possible, we'll keep you informed on the expected release date.
